Otabek Kadirov
IT-forward/js-fn-rock-paper-scissors pull request #5
Opened 2020-12-22 07:44 UTC by Otabekkadirov

o'xshatishga harakat qilyapman...

2020-12-23 11:57 UTC, Otabekkadirov commented
The game is ready to play

2020-12-24 01:46 UTC, bahriddin requested changes
Bitta o'zgarish qilishingiz kerak. Qolgani yaxshi 👍

2020-12-24 01:46 UTC, bahriddin commented on index.js
> +  console.log(userChoice, computerChoice);
Mana shu joyida kim qaysi tanlov qilganini tushunish qiyinroq. Mana bunaqa chiqsin ekranda:
```
User chose: paper
Computer chose: rock
User won
```

2020-12-24 01:48 UTC, bahriddin commented on index.js
> +  let input = userInput.trim().toLowerCase();
cleanInput deb nomlasangiz o'zgaruvchi nomini yanayam tushunarliroq bo'lardi.

2020-12-24 12:01 UTC, bahriddin approved these changes

2020-12-24 12:01 UTC, closed without merging